---
- name: Reboots devices
  reboot:
  become: yes
  tags:
    - never
    - reboot

- name: Swap file creation
  import_tasks: swapfile.yml
#  delegate_to: localhost
  tags:
    - swap_file

- name: Get host docker infos
  import_tasks: docker_info.yml
  tags:
    - never
    - docker-info
