- name: Install ansible sandbox
  hosts: all
  tasks:
    - name: Install updates
      apt:
        update_cache: yes
        upgrade: 'yes'
        force_apt_get: yes
      become: yes
      tags:
        - update_sandbox

- name: Setup users
  hosts: all
  roles:
    - name: users
  tags:
    - users

- name: Install sandbox
  hosts: all
  roles:
    - name: comfort
  tags:
    - comfort

- name: Setup docker
  hosts: all
  roles:
    - name: docker
  tags:
    - docker

- name: Setup services
  hosts: all
  roles:
    - name: services
  tags:
    - services

- name: Setup maintenance
  hosts: all
  roles:
    - name: maintenance
  tags:
    - maintenance

- name: Setup api
  hosts: all
  roles:
    - name: services/API/kata-api
  tags:
    - api
