- name: Install ansible sandbox
  hosts: all
  tasks:
    - name: Install updates
      apt:
        update_cache: yes
        upgrade: 'yes'
        force_apt_get: yes
      become: yes
      tags:
        - update_sandbox

- name: Setup users
  hosts: all
  roles:
    - name: users
  tags:
    - users

- name: Install sandbox
  hosts: all
  roles:
    - name: comfort
  tags:
    - comfort

- name: Setup docker
  hosts: all
  roles:
    - name: docker
  tags:
    - docker
