---
- name: install useful packages
  apt:
    name:
      - htop
      - acl
      - vim
      - git
      - git-extras
      - tmux
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install
