---
- include_vars: ../../users/vars/main.yml
  tags:
    - always

- name: ensure group docker exists
  group:
    name: docker
    state: present
  become: yes
  tags:
    - add-group-docker

- name: ensure dojo user in docker group
  user:
    name: dojo
    append: yes
    groups: docker
    state: present
  become: yes
  tags:
    - add-dojo-group-docker
    - add_all_user_dockergroup

- name: ensure ubuntu user in docker group
  user:
    name: ubuntu
    append: yes
    groups: docker
    state: present
  become: yes
  tags:
    - add-ubuntu-group-docker
    - add_all_user_dockergroup

- name: ensure main users in docker group
  user:
    name: "{{ item.name }}"
    append: yes
    groups: docker
    state: present
  become: yes
  with_items: "{{ vmusers }}"
  tags:
    - add-main-group-docker
    - add_all_user_dockergroup

- name: install docker package
  apt:
    name: docker.io
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install-docker

- name: remove pip docker-py
  pip:
    name: docker-py
    state: absent
  become: yes

- name: install docker for pip
  pip:
    name: docker
    state: present
  become: yes

- name: start service docker, if not started
  service:
    name: docker
    state: started
  become: yes
  tags:
    - start-docker-service
